[workspace]
members = [
    "crates/cas-core",
    "crates/cas-cli",
    "crates/cas-gui",
]
resolver = "2"

[workspace.package]
version = "0.1.37"
edition = "2024"
license = "Unlicense"

[workspace.dependencies]
atomic-write-file = "0.3.1"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.29"
dirs = "6"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
sysinfo = "0.37"
tempfile = "3"
thiserror = "2"
toml = "0.9"
uuid = { version = "1", features = ["v4", "serde"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
webbrowser = "1.2.2"
unicode-width = "0.2.2"
sys-locale = "0.3.2"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
